#!/bin/bash
valid=true  #made all lowercase and removed spaces 
count=1
while [ $valid ] #added a $ in front
do
echo $count #added a $ in front
if [ $count -eq 5]; #added a $ in front
then
break
fi
((count++))
done
